### ISSUE TITLE
tar_data.extractall(path=data_app_dir) -> type error join() 'PosixPath'

### ISSUE THREAD

**Issue by evrards** [RealityNet/kobackupdec#14]
Hello,
Trying to decode a backup done running Android 10.
Each application found send this error :

INFO:root:working on be.appsolution.lotterienationale.tar
Traceback (most recent call last):
  File "./kobackupdec.py", line 622, in <module>
    main(user_password, backup_path, dest_path)
  File "./kobackupdec.py", line 493, in main
    tar_data.extractall(path=data_app_dir)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2036, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by lp4n6** [comment]
This issue is probably not related to the Android version, nor the backup app version. I run the script flawlessly with Python 3.7. Could you try with that versino?

Regards.

**Comment by evrards** [comment]
You're right, it works perferctly with python3.7.

Thanks :)
