### ISSUE TITLE
Memory Error on large .tar

### ISSUE THREAD

**Issue by k-jansen** [RealityNet/kobackupdec#22]
I am encountering the following memory error on two files of the backup:
```
INFO:root:working on com.moonactive.coinmaster.apk
INFO:root:working on com.moonactive.coinmaster.tar
Traceback (most recent call last):
  File "kobackupdec.py", line 932, in <module>
    main(user_password, backup_path, dest_path)
  File "kobackupdec.py", line 866, in main
    decrypt_backup(password, files_folder, dest_path_out)
  File "kobackupdec.py", line 810, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out)
  File "kobackupdec.py", line 693, in decrypt_files_in_root
    cleartext = decrypt_entry(decrypt_info, entry,
  File "kobackupdec.py", line 649, in decrypt_entry
    cleartext = decrypt_info.decryptor.decrypt_package(
  File "kobackupdec.py", line 303, in decrypt_package
    return decryptor.decrypt(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\_mode_ctr.py", line 253, in decrypt
    plaintext = create_string_buffer(len(ciphertext))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 63, in create_string_buffer
    buf = buftype()
MemoryError
```
The .tar of the said files are 1.1GB and 695MB. Once I delete them the scrip decodes the backup fine. The 460MB file, also works without an issue.

**Comment by dfirfpi** [comment]
Thanks @k-jansen .
Indeed I try to untar / tar in memory, without explicitly using files on disk. Large tar could get this issue. I'm unsure if to change the code... anyhow, as a workaround, you can grab the decryption code from Python and use it just again those large files.

**Comment by bobjane-t-mart** [comment]
This shouldnt be closed - the issue still exists.
