### ISSUE TITLE
Fails at start of app data unpacking

### ISSUE THREAD

**Issue by Mohsyn** [RealityNet/kobackupdec#30]
decrypting and un-TAR-ing packages to destination...
working on aca.db.tool.tar
working on adrian.adbm.pro.tar

Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at kobackupdec.Program.kobackupdec.TAR_Extract(Stream inputStream, String outputDir)
   at kobackupdec.Program.kobackupdec.decrypt(String user_password, String backup_path_in, String dest_path_out)
   at kobackupdec.Program.Main(String[] args)

**Comment by Mohsyn** [comment]
There are colons :  in Filename
🤔

**Comment by dfirfpi** [comment]
Try to not use the -e option (do not expand TARs). You can do it later manually with different tools.
I assume you're using Windows...

**Comment by Mohsyn** [comment]
> Try to not use the -e option (do not expand TARs). You can do it later manually with different tools.
> I assume you're using Windows...

Yes I am on windows and I could not find -e option anywhere in script. Please guide on how to workaround this issue.


Another thing I want to ask was about a link in the script https://stackoverflow.com/questions/8863875/decompress-tar-files-using-c-sharp

There is an answer in the end on using SharpCompress library
Will that be a viable option ?

**Comment by Mohsyn** [comment]
Problem solved - Thanks
