### ISSUE TITLE
Fails @ Large Files

### ISSUE THREAD

**Issue by Mohsyn** [RealityNet/kobackupdec#31]
**Describe the bug**
Apparently fails on handling a large sized file.

**Required info (please complete the following information):**
 - Huawei Kobackup version: 20200611
 - Host: [Windows / Linux ] Windows
 - Kobackup script version: 20200611
 - Kobackup output log (use -vvv) used -v 

**Additional context**

WARNING:root:Decryption material checks failed for by.androld.app.dbreader, type BackupFileModuleInfo
WARNING:root:Decryption material checks failed for com.mxtech.videoplayer.ad, type BackupFileModuleInfo
WARNING:root:Decryption material checks failed for per.pqy.openjdk, type BackupFileModuleInfo
WARNING:root:entry backupinfo.ini unmanged, copying it
WARNING:root:entry cinfoset.dat unmanged, copying it
Traceback (most recent call last):
  File "D:\Python\kobackupdec-master\kobackupdec.py", line 1009, in <module>
    main(user_password, backup_path, dest_path, args.expandtar, args.writable)
  File "D:\Python\kobackupdec-master\kobackupdec.py", line 937, in main
    decrypt_backup(password, files_folder, dest_path_out, expandtar)
  File "D:\Python\kobackupdec-master\kobackupdec.py", line 881, in decrypt_backup
    decrypt_files_in_root(decrypt_info, path_in, path_out, expandtar)
  File "D:\Python\kobackupdec-master\kobackupdec.py", line 764, in decrypt_files_in_root
    for x in decrypt_large_entry(decrypt_info, entry,
  File "D:\Python\kobackupdec-master\kobackupdec.py", line 699, in decrypt_large_entry
    decrypt_material, entry.read_bytes()):
  File "D:\Python\Python38-32\lib\pathlib.py", line 1226, in read_bytes
    return f.read()
MemoryError

**Comment by Mohsyn** [comment]
Sorry Just realized - this issue is reported already

**Comment by dfirfpi** [comment]
closing then, thanks.
