### ISSUE TITLE
Getting an Attribute Error

### ISSUE THREAD

**Issue by Aightek** [RealityNet/kobackupdec#33]
Hi there,

I am getting this error at the start of decrypting process;

I Backed up with a MacOS Sierra and trying to Decrypt it with an Win10.

```
DEBUG:root:Ignoring HeaderInfo entry.
DEBUG:root:Ignoring BackupFilePhoneInfo entry
DEBUG:root:Ignoring BackupFileVersionInfo entry
DEBUG:root:Parsing BackupFilesTypeInfo
DEBUG:root:crypto_init: using version 3.
DEBUG:root:SHA256(BKEY)[16] = b'710689d6ff0e681686b6a7f61c3d0d64'
DEBUG:root:SALT[32] = b'd79a63d2037afc04a98f957e48d1a4ed87ec7e8933927f2b3f7ebfa1adb85257'
DEBUG:root:KEY check expected = b'0fc3a722a7d82559eaa7b95d8ba1717fd74f5a4ea627082a181c1f721a06087f'
DEBUG:root:RESULT = b'0fc3a722a7d82559eaa7b95d8ba1717fd74f5a4ea627082a181c1f721a06087f'
INFO:root:OK, backup key is correct!
INFO:root:parsing xml file document.xml
INFO:root:parsing xml file picture.xml
Traceback (most recent call last):
  File "kobackupdec.py", line 1013, in <module>
    main(user_password, backup_path, dest_path, args.expandtar, args.writable)
  File "kobackupdec.py", line 941, in main
    decrypt_backup(password, files_folder, dest_path_out, expandtar)
  File "kobackupdec.py", line 881, in decrypt_backup
    parse_generic_xml(entry, decrypt_info)
  File "kobackupdec.py", line 652, in parse_generic_xml
    path = entry.getElementsByTagName('Path')[0].firstChild.data
AttributeError: 'NoneType' object has no attribute 'data'
```
Any help would be appreciated!
Thanks,

**Comment by dfirfpi** [comment]
hi @Aightek, thanks for the feedback.
It seems the picture.xml is not perfectly parsed or it does not contain what is expected.
It would be extremely beneficial to have the document and picture xml files. Do you think is it possible?

**Comment by Adfighting** [comment]
Hello,

I would like to ask about the role of checkMsgV3.

thanks..
@dfirfpi

**Comment by dfirfpi** [comment]
Not an issue.
