### ISSUE TITLE
Hit "UnicodeDecodeError" when decode first file

### ISSUE THREAD

**Issue by vanishedtest** [RealityNet/kobackupdec#36]
**Describe the bug**
Hit "UnicodeDecodeError" when try to decode the first file from the backup stored by HiSuite (mac version 10.0.1.300)

**NOTE**
Previously I backup using HiSuite from my Mac book, when I tried to use another Windows 10 Laptop and following the python to decrypt it, I hit the error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte".

**Required info (please complete the following information):**
 - Huawei Kobackup version: HiSuite Mac version 10.0.1.300
 - Host: Windows 10, python 3.7.
 - Kobackup script version:
 - Kobackup output log (use -vvv):
"INFO:root:parsing xml file ._audio.xml
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\kobackupdec-master\kobackupdec.py", line 1013, in <module>
    main(user_password, backup_path, dest_path, args.expandtar, args.writable)
  File "C:\Users\xxxx\Downloads\kobackupdec-master\kobackupdec.py", line 941, in main
    decrypt_backup(password, files_folder, dest_path_out, expandtar)
  File "C:\Users\xxxx\Downloads\kobackupdec-master\kobackupdec.py", line 881, in decrypt_backup
    parse_generic_xml(entry, decrypt_info)
  File "C:\Users\xxxx\Downloads\kobackupdec-master\kobackupdec.py", line 644, in parse_generic_xml
    xml_dom = xml.dom.minidom.parse(xml_file)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\xml\dom\minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\xml\dom\expatbuilder.py", line 913, in parse
    result = builder.parseFile(file)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\xml\dom\expatbuilder.py", line 204, in parseFile
    buffer = file.read(16*1024)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte"

**Additional context**
I have double check from MacBook, that file "._audio.xml" is charset=utf-8

**Screenshots**

**Comment by oO0oO0oO0o0o00** [comment]
Then it's strange. You can make a copy of the file, wipe out any possible personal data from it by replacing such words with arbitrary character of your choice and post it here. The chosen character shall be from the **same language** with the characters being wiped out to best help locate the bug. If the file is long, you can provide only the first 50 characters or the first 10 lines. It said "position 37" and it said it was using a buffer of size 16*1024 bytes that generally a `xml` file would adequately fit in, then it should have meant the 37th byte or 19th character.

**Comment by dfirfpi** [comment]
Hi @vanishedtest ,
I have no time to reproduce all the scenario.  Without any data I must close this issue.
