### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

### ISSUE THREAD

**Issue by OpflBopfl** [RealityNet/kobackupdec#45]
Hi

I backed up my Huawei P30 pro (complete backup) and now I try to decrypt the files to get access to a few documents and mainly mp3 files I used on my phone.

I get a strange error:

--- snip ---

Traceback (most recent call last):
  File "./kobackupdec.py", line 1014, in <module>
    main(user_password, backup_path, dest_path, args.expandtar, args.writable)
  File "./kobackupdec.py", line 941, in main
    decrypt_backup(password, files_folder, dest_path_out, expandtar)
  File "./kobackupdec.py", line 881, in decrypt_backup
    parse_generic_xml(entry, decrypt_info)
  File "./kobackupdec.py", line 644, in parse_generic_xml
    xml_dom = xml.dom.minidom.parse(xml_file)
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 913, in parse
    result = builder.parseFile(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 204, in parseFile
    buffer = file.read(16*1024)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

--- snap ---

Any thoughts? Is it password related? I had troubles to hand over my password, because it contains an "!".
When I hard code the password (line 1000 -> user_password = 'PASSWORD_starts_with_!'.encode('utf-8'), I get the same error ...
Is there a way to maybe pass the hash to decrypt instead of plain password?

**Comment by aLCoLoNeL** [comment]
Same issue for me ..

**Comment by holgus103** [comment]
If you guys are on MacOS and are using a non native partition then check this out:
https://github.com/RealityNet/kobackupdec/pull/46

I had exactly the same problem and it was caused by how Mac handles extended attributes on my external HDD (exFAT)

**Comment by OpflBopfl** [comment]
Thanks man ... Saved my life. Works now with one little exception.
Can't process the pictures ... Throws an error while processing the picture.xml. I renamed the file and now processing is up and running!

--- snip ---

INFO:root:parsing xml file picture.xml
Traceback (most recent call last):
  File "./kobackupdec/kobackupdec.py", line 1014, in <module>
    main(user_password, backup_path, dest_path, args.expandtar, args.writable)
  File "./kobackupdec/kobackupdec.py", line 941, in main
    decrypt_backup(password, files_folder, dest_path_out, expandtar)
  File "./kobackupdec/kobackupdec.py", line 881, in decrypt_backup
    parse_generic_xml(entry, decrypt_info)
  File "./kobackupdec/kobackupdec.py", line 652, in parse_generic_xml
    path = entry.getElementsByTagName('Path')[0].firstChild.data
AttributeError: 'NoneType' object has no attribute 'data'

--- snap ---
